# Generated by Django 4.1.5 on 2023-01-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('gender', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=50)),
                ('qrcode', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
