# Generated by Django 4.1.5 on 2023-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('idAccess', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('idPortique', models.IntegerField(max_length=70)),
                ('dateAccess', models.DateField(max_length=50)),
            ],
            options={
                'db_table': 'Access',
            },
        ),
    ]
